### ISSUE TITLE
CAB403 - Assignment 2 - Clean and check

### ISSUE THREAD

**Issue by JimmyBoon** [JimmyBoon/CAB403#10]
- [x] Card Reader Controller in full #21 
- [x] Fire Alarm Call Point Controller in full #20 
- [x] Door controller, but not "Close Secure" #19 
- [x] Fire Alarm Unit, with no Temp updates. Can only be raised with manual call points #18 
- [x] Overseer, nothing with share memory, elevator, temp sensor, camera, destination selector #17 
- [x] Simulator with only CARD_SCAN and CALL_POINT_TRIGGER #16

**Comment by JimmyBoon** [comment]
- [x] Input checks
- [x] Malloc remove
- [x] Function description check
- [x] Final TODOs
- [x] Tidy

**Comment by JimmyBoon** [comment]
Card Reader checked against sample output 1 - Perfect, Clean, Description ok
Door 1, ok
Door 2, gives overseer error. Connection refused.
Door 3, ok
Callpoint 1 - ok - Clean, Description ok
FireAlarm - Ok - Clean Description ok
FireAlarm2 - ok
Overseer - ok - Description ok
Simulator 1 - ok
Simulator 2 - Crashing
